name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main  # Adjust this to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # The job will run on a virtual Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This will check out your repository's code

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3  # Sets up SSH authentication
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add the private SSH key from GitHub Secrets

    - name: Deploy to VPS
      run: |
        # Ensure SSH can connect without strict host key checking
        ssh -o StrictHostKeyChecking=no root@103.168.18.92 -p 7576 << 'EOF'
          # Source NVM to ensure the correct Node environment is loaded
          source /root/.nvm/nvm.sh
          nvm use 18.0.0  # Ensure the correct Node.js version is used (e.g., Node.js 18.x)

          # Navigate to the Next.js app directory
          cd /var/www/tcladminapp || exit 1  # Ensure the directory exists

          # Stash any local changes to avoid merge conflicts
          git stash || true  # 'true' ensures it doesn't fail if there's nothing to stash

          # Pull the latest changes from GitHub
          git pull origin main

          # Optionally, apply the stashed changes (if any)
          git stash pop || true

          # Install or update dependencies
          npm install

          # Remove the existing .next directory to avoid old builds
          rm -rf .next || true

          # Run the build to generate .next directory
          npm run build || exit 1  # Ensure build is successful

          # Debugging step: List contents of .next folder for confirmation
          ls -R .next || exit 1  # Exit if .next folder is missing

          # Kill any process on port 4000 just in case
          sudo fuser -k 4000/tcp || true

          # Delete ALL existing "nextjs-app admin" processes
          /root/.nvm/versions/node/v18.0.0/bin/pm2 delete "nextjs-app admin" || true

          # Start the app fresh
          /root/.nvm/versions/node/v18.0.0/bin/pm2 start npm --name "nextjs-app admin" -- start --update-env

          # Save PM2 state
          /root/.nvm/versions/node/v18.0.0/bin/pm2 save

        EOF
